In [2]:
import random
a=random.random()
print(a)

0.03419564793026897


- include upperbond

In [3]:
b=random.randint(1,10)
print(b)

2


In [4]:
c=random.uniform(1,10)
print(c)

1.757862150966258


- exclude upperbond

In [5]:
a=random.randrange(1,10)
print(a)

9


- mean of 0 standard deviation of 1

In [7]:
a=random.normalvariate(0,1)
print(a)

0.4472299675336621


- to work with sequences

In [10]:
mylist=list("ABCDEF")
a=random.choice(mylist)
print(a)

E


In [14]:
a=random.sample(mylist,2)
print(a)

['A', 'D']


In [17]:
a=random.choices(mylist,k=3)
print(a)

['B', 'B', 'E']


In [18]:
a=random.shuffle(mylist)
print(a)

None


In [22]:
import random
random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(2)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.13436424411240122
2
0.9560342718892494
1


- for security purposes use secrets

In [24]:
import secrets

a=secrets.randbelow(10)
print(a)

2


In [26]:
b=secrets.randbits(4)
print(b)

3


In [27]:
mylist=list("ABCDEFG")
a=secrets.choice(mylist)
print(a)

E


In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [33]:
import numpy as np

a=np.random.rand(3)

b=np.random.rand(3,3)
print(a)
print(b)

[0.39577791 0.03783411 0.50966223]
[[0.92314193 0.19288021 0.95221067]
 [0.14660205 0.69713728 0.64554849]
 [0.15605274 0.01736401 0.76982545]]


In [34]:
c=np.random.randint(0,10,(3,4))
print(c)

[[7 1 1 7]
 [8 7 7 2]
 [4 3 9 0]]


In [36]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
np.random.shuffle(arr)